### ISSUE TITLE
Docs Website: Tooltip placement should be in a different order

### ISSUE THREAD

**Issue by 0x3333** [sailboatui/sailboatui#13]
Docs Website: https://sailboatui.com/docs/components/tooltip/#Placement

The order of the buttons on the Tooltip page is weird, I believe it should be: Left, Top, Bottom, and Right.

Currently, it shows the tooltip on top of the other buttons, the order I propose, it will display without being on top of other components.
![image](https://user-images.githubusercontent.com/289289/210240094-66154b00-1bf7-4d92-ba55-31d66bd903ee.png)

**Comment by lvwzhen** [comment]
We are referring to the order of tooltips in bootstrap, I don't think this is a bug, thank you.
