### ISSUE TITLE
Docs Website: Tooltip animation tooltip text is wrong.

### ISSUE THREAD

**Issue by 0x3333** [sailboatui/sailboatui#14]
Docs Website: https://sailboatui.com/docs/components/tooltip/#Animation

In the Tooltip page, Animation section, the tooltip text is incorrect:

![image](https://user-images.githubusercontent.com/289289/210241118-99e64aa9-4cd0-4841-9d0a-48cf3c10ecd7.png)

Could be used in the same order as I suggested in issue #1, in this way, the user will see the animation on all placements.

**Comment by lvwzhen** [comment]
[Fix typo](https://github.com/sailboatui/sailboatui/commit/e4635439d878d3a73bbf0c8ca1d391af050516a5)

**Comment by 0x3333** [comment]
Damn, my bad, I didn't notice the docs are on the same repo. Next time I'll issue a PR.

**Comment by lvwzhen** [comment]
It's ok, Sailboat UI is just the beginning, we didn't describe it clearly.
