### ISSUE TITLE
Docs Website: Drop down Splitted button misspleed.

### ISSUE THREAD

**Issue by 0x3333** [sailboatui/sailboatui#17]
Docs Website: https://sailboatui.com/docs/components/dropdown/#Splitd%20button

The splitted button is misspelled in the header. It says Splitd.

![image](https://user-images.githubusercontent.com/289289/210242628-a0dd32b7-cce0-4811-acbc-9feccdd38c08.png)

**Comment by lvwzhen** [comment]
[Fix "Docs Website: Drop down Splitted button misspleed. "](https://github.com/sailboatui/sailboatui/commit/cb3736761fa1bed69b28cf4ce6fd1cd7ae9ac549)
