### ISSUE TITLE
Docs Website: Textarea validation error doesn't have the red border like input

### ISSUE THREAD

**Issue by 0x3333** [sailboatui/sailboatui#18]
Docs Website: https://sailboatui.com/docs/forms/textarea/#With%20validation%20error

In the Textarea validation error example, the border is not red like the other inputs:

![image](https://user-images.githubusercontent.com/289289/210242970-470804f1-7633-46f2-a69a-0891564f68f9.png)

![image](https://user-images.githubusercontent.com/289289/210242946-895957b1-f2e4-43c6-85d8-4a7136be30f3.png)

![image](https://user-images.githubusercontent.com/289289/210243068-6659d7cb-b6a9-4ccb-bb81-4f7b07ed1b1d.png)

**Comment by lvwzhen** [comment]
[Fix Docs Website: Textarea validation error doesn't have the red bord…](https://github.com/sailboatui/sailboatui/commit/9250c9dcb08b6a028ea0f0dc83bcf47b87b201db)

**Comment by lvwzhen** [comment]
[Fix Docs Website: Textarea validation error doesn't have the red bord…](https://github.com/sailboatui/sailboatui/commit/9250c9dcb08b6a028ea0f0dc83bcf47b87b201db)
