### ISSUE TITLE
typo/fix-index-typo

### ISSUE THREAD

**Issue by JoshKleineDeters** [sailboatui/sailboatui#50]
### Description

Sailboat UI is a modern UI component library for Tailwind CSS. Get started with 150+ open source Tailwind CSS components, make it easy to build you products.

### Expected behavior

Sailboat UI is a modern UI component library for Tailwind CSS. Get started with 150+ open source Tailwind CSS components, make it easy to build ```your``` products.

---
Very excited to work with this library. Very reminiscent of Chakra-ui (my current favourite)

**Comment by lvwzhen** [comment]
Thanks for your support
