### ISSUE TITLE
Docs: Contributing guide

### ISSUE THREAD

**Issue by tlarnold10** [sailboatui/sailboatui#77]
### Description

Would be great if there were a contribution guide of some kind. Not sure if that is needed at this point, but it might get more people interested in contributing as well. Just a through, and I would be open to assisting if you need it.

**Comment by lvwzhen** [comment]
Welcome to PR

**Comment by tlarnold10** [comment]
Created PR: https://github.com/sailboatui/sailboatui/pull/78
